### ISSUE TITLE
How to know available states from the current one?

### ISSUE THREAD

**Issue by hosseio** [gmorel/StateWorkflowDemo#2]
Hi, 
I please would like to know how to get the following possible states from the current one.
I have declare a new getActionName() function to the BookingStateInterface interface. Example: For the StateCancel it returns the "cancel booking" string. So I have something like the following in mind:

```
//...
$actions = array();
foreach ($booking->getState($stateWorkflow)->getFollowingStates() as $state) {
    $actions[] = $state->getActionName();
}
```

Thanks in advance

**Comment by gmorel** [comment]
Hi, 

StateWorkflow is not able to do that natively.

However, maybe by doing something like this using Reflexion: 

``` php
$currentState = $booking->getState($stateWorkflow);

// Extract available transitions (ie. methods) from Custom State Interface
$reflexion = new ReflectionClass($currentState);

// Only public methods and implemented ones in your State
// If you "cheat" by setting all your transition methods as "final" 
// final public function setBookingAsWaitingForPayment(HasStateInterface $booking)
// It will no more be mockable though
$methods = $reflexion->getMethods(ReflectionMethod::IS_PUBLIC | ReflectionMethod::IS_FINAL);

$availableTransitions = array();
foreach($methods as $method) {
    $availableTransitions[$method->name];
}

```

However if one day you forgot to add the **final** keyword in you method. It will be hard to debug.. So hard to maintain.

I'll try to come up with a better solution based on 

``` php
public function isSupporting($methodName) {
    // ...
}
```

Cheers

**Comment by hosseio** [comment]
I am starting to read the [SpecGen - State Workflow Bundle](https://github.com/spec-gen/state-workflow-spec-gen-bundle) project to see how the transitions are generated for printing them, but the solution you have just proposed is good enough. I am thinking in who needs to have this responsabliity, and I think that a new class is the best way.
BTW, great great work, I really appreciate it. I have NO time now, but I would like to contribute some way to thank you.
